Feature/no ref/projectcard
lushi-liu/PortfolioJSM pull request #6
Opened 2023-09-11 05:00 UTC by lushi-liu

- Need to decide how to get the image set up and how to present them

![Screenshot 2023-09-11 010021](https://github.com/lushi-liu/PortfolioJSM/assets/117430261/49f0c595-eb65-4eca-b0ec-bb3340177ea5)

2023-09-11 13:10 UTC, brandonetter requested changes
As far as your comment about images for those display sections- look into "overflow-hidden" and positioning.

2023-09-11 13:10 UTC, brandonetter commented on portfolio-jsm/src/components/ProjectCard.tsx
> +              height={""}
Try making the props optional in the Button interface so you don't need to include things you're not using. You're already doing so with some of the props.

2023-09-11 13:10 UTC, brandonetter commented on portfolio-jsm/src/components/ProjectCard.tsx
> +                height={""}
Same here

2023-09-11 13:10 UTC, brandonetter commented on portfolio-jsm/src/components/NavBar.tsx
> +          )}
This is fine. But you can just use a ternary on the image src itself.

2023-09-11 13:10 UTC, brandonetter commented on portfolio-jsm/src/components/Input.tsx
> +      }
```suggestion
  let onClick;
  
  if (type === "Time") {
    onClick = (e: React.MouseEvent<HTMLInputElement>) => {
      e.currentTarget.showPicker();
    };
  }

  return (
    <input
      type={type}
      onClick={onClick}
      placeholder={placeholder}
      className={`block rounded-[10px] ${inputColor} px-4 py-2`}
      style={inputStyle}
      onChange={onChange}
    />
  );
```

Not a huge fan of this ternary. Consider this

2023-09-12 01:18 UTC, lushi-liu commented on portfolio-jsm/src/components/Input.tsx
> +      }
I realized I'm not going to use the time picker property so I removed it

2023-09-12 16:35 UTC, brandonetter requested changes
Good work so far. One small change for accessibility

2023-09-12 16:35 UTC, brandonetter commented on portfolio-jsm/src/components/NavBar.tsx
> +            alt=""
Let's add an 'alt' here for accessibility

2023-09-12 17:07 UTC, brandonetter commented on portfolio-jsm/src/components/NavBar.tsx
> +            alt=""
Once that's fixed you can merge this

2023-09-12 18:17 UTC, merged