started implementing project page, image not loading however
lushi-liu/PortfolioJSM pull request #8
Opened 2023-09-18 03:42 UTC by lushi-liu

![Screenshot 2023-09-17 234147](https://github.com/lushi-liu/PortfolioJSM/assets/117430261/07424698-ca99-4b01-9294-cc699c208b16)

2023-09-18 21:20 UTC, brandonetter requested changes
![image](https://github.com/lushi-liu/PortfolioJSM/assets/4108484/8ad81b8b-00ec-4959-a712-bbb6c7fd1b03)

Light mode text is impossible to read. You're also making the same error with relative paths for all the images in your navbar:
![image](https://github.com/lushi-liu/PortfolioJSM/assets/4108484/9268549c-5c3f-43b8-9fef-52860f558d8f)


Remove the `.` before each path or it will stop working when your URL is no longer at the root of the directory.

2023-09-18 21:20 UTC, brandonetter commented on portfolio-jsm/src/app/casestudies/morrent/page.tsx
> +        mImage="./job-image/Morrent-Mobile.svg"
```suggestion
        lImage="/job-image/Morrent-Laptop.svg"
        mImage="/job-image/Morrent-Mobile.svg"
```

Don't use a relative path here, that's why the image isn't loading.

2023-09-18 21:20 UTC, brandonetter commented on portfolio-jsm/src/app/casestudies/morrent/page.tsx
You should really consider using slugs and then retrieving the relevant data based on the name:

https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes#example

That way, instead of writing different pages for each project- you simple have to map the name in the slug to some data in sanity or in your JSON files. This approach is extendable.

2023-09-21 05:50 UTC, lushi-liu commented
![Screenshot 2023-09-21 014908](https://github.com/lushi-liu/PortfolioJSM/assets/117430261/7df10d58-e538-4cfa-9dc9-137dcb8e5727)
![Screenshot 2023-09-21 014955](https://github.com/lushi-liu/PortfolioJSM/assets/117430261/e042b963-0cd5-4b86-b62a-1deda1827139)

2023-09-28 16:50 UTC, merged